#main program
import exceptions

def main():
    exceptions.open_file_for_reading('names.text')
    

main()