#main program
import exceptions

def main():
    result = exceptions.divide_two_numbers(6, 2)
    print(result)
    
    result = exceptions.divide_two_numbers(3, 0)
    print(result)
    

main()